#pragma config(Sensor, dgtl12, green,          sensorLEDtoVCC)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:Controlling LEDs
  Team Members: Jessica W, Jessica L, Josh, Joel
  Date:2/7/19
  Section:N/A


  Task Description:turn on LED


  Pseudocode:

*/

task main()

{                                     //Program begins, insert code within curly braces

turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);
wait(1);
turnLEDOn(green);
wait(1);
turnLEDOff(green);

}
