#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftmotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Optical Shaft Encoder
  Team Members: Jessica W, Jessica L, Josh, Joel
  Date:2/11/19
  Section: Fab


  Task Description:


  Pseudocode:

*/

task main()
{                                     //Program begins, insert code within curly braces

startMotor(leftMotor, 63);
startMotor(rightMotor, 63);
untilEncoderCounts(480,quad);
stopMotor(leftMotor);
stopMotor(rightMotor);

}
