#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servomotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:Controlling one motor
  Team Members:Jessica L, Jessica W, Josh, Joel
  Date:2/11/19
  Section: Fab


  Task Description:


  Pseudocode:
  turn the right motor forward at half speed for 5 secs
  stop the motor

*/

task main()
{                                     //Program begins, insert code within curly braces
startMotor(rightMotor, 100);
wait(5);
stopMotor(rightMotor);
}
