#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title:3.1.2 Basic Outputs Programming Part 4
  Team Members:Jessica L, Jessica W, Joshua, Joel
  Date:2/11/19
  Section:N/A


  Task Description:Controlling a servomotor


  Pseudocode:start at ccw 60 degrees(-127), wait 2 seconds, turn 60 degrees(0),
  wait 2 seconds, turn 60 degrees cw(127), wait 2 seconds

*/

task main()
{
setServo(servoMotor, -127);//start at 60 degrees ccw
wait(2);//waits 2 seconds
setServo(servoMotor, -63);//turn 30 degrees cw
wait(3);//waits 3 seconds
setServo(servoMotor, 0);//turn 30 degrees cw
wait(2);//waits 2 seconds
setServo(servoMotor, 63);//turn 30 degrees cw
wait(3);//waits 3 seconds
setServo(servoMotor, 127);//turn 30 degrees cw
wait(2);//waits 2 seconds
                                            //Program begins, insert code within curly braces

}
