#pragma config(Motor,  port2,           rightMotor,    tmotorNone, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: A1_1_2 Part 3
  Team Members: Josh, Joel, Jessica, Jessica
  Date: 2/7/19
  Section: N/A


  Task Description: control two motors


  Pseudocode:

  a.Turn the rightMotor on forward at half speed for 5 seconds, and then stop.
	b. Turn the leftMotor on in reverse at three-fourths speed for 2.5 seconds, and then stop.
	c. Turn both motors on at full power while spinning in the same direction for 7.25 seconds,
	and then stop.



*/

task main()
{                                     //Program begins, insert code within curly braces




}
