#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightsensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  leftLimit,      sensorTouch)
#pragma config(Sensor, dgtl2,  rightLimit,     sensorTouch)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           lowerMotor,    tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           openMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
Project Title:Inputs and Outputs
Team Members: Jessica W, Jessica L, Josh, Joel
Date:2/27/19
Section:Fab Room


Task Description: To create a crane that can pick up an object and drop it to a designated location


Pseudocode:
...

*/
int sonarValue = 15;

void openTheCrane()
{
	startMotor(openMotor,100);				//opens the crane
	wait(0.5);
	stopMotor(openMotor);
}
void closeTheCrane()
{
	startMotor(openMotor,-100);			//closes the crane
	wait(0.5);
	stopMotor(openMotor);
}
void lowerTheCrane()
{
	startMotor(lowerMotor,-100);			//lowers the crane
	wait(0.7);
	stopMotor(lowerMotor);
}
void raiseTheCrane()
{
	startMotor(lowerMotor,100);					//start raising the crane
	wait(0.9);
	stopMotor(lowerMotor);
}

void rightMove(){
	startMotor(leftMotor,20);
	startMotor(rightMotor,20);
	waitUntil(SensorValue(sonar) < sonarValue);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}
void leftMove(){
	startMotor(leftMotor,-20);
	startMotor(rightMotor,-20);
	waitUntil(SensorValue(sonar) < sonarValue);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}

void moveLeft(){
	startMotor(leftMotor,20);
	startMotor(rightMotor,20);
	waitUntil(SensorValue(leftLimit) == 1);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}

void moveRight(){
	startMotor(leftMotor,-20);
	startMotor(rightMotor,-20);
	waitUntil(SensorValue(rightLimit) == 1);
	stopMotor(leftMotor);
	stopMotor(rightMotor);
}

task main()
{

	//raiseTheCrane();
while(true){
	waitUntil(SensorValue(lineFollower) < 3000);    //linefollower detects an object
	rightMove();                                  //move the car to the object
	openTheCrane();																	//open the crane
	int sensorValue = SensorValue(lineFollower);
	lowerTheCrane();																//lower the crane
	closeTheCrane();																//close the crane
	raiseTheCrane();																//raise the crane
	if(sensorValue < 1000){													//if the line follower detects bright color
		moveRight();																	//move right till the limit switch is presed
		wait(1);
		openTheCrane();																//open the crane to drop the object
		closeTheCrane();															//close the
		rightMove();
		if(SensorValue(rightLimit)==1){
			rightMove();
		}
	}
	if(sensorValue > 1000){                     		//if it is a dark color
		moveLeft();																			//move left till the limit switch is pressed
		wait(1);
		openTheCrane();																//open the crane to drop the object
		closeTheCrane();
		if(SensorValue(leftLimit)==1){
			leftMove();
		}

	}
}
}
